runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static

- url: /.*
  script: auto

env_variables:
  DJANGO_wishlist_USER_PASSWORD: Mouhamad

beta_settings:
  cloud_sql_instances: django-wishlist-app:us-central1:wishlist-db